### ISSUE TITLE
bug：OMV7运行报错，m-team页面报错“請求過於頻繁”

### ISSUE THREAD

**Issue by Walleloveeve** [xiaohaiGreen/mteam-active-top-rss#3]
您好，我在自己的nas上面运行该docker镜像，出现了以下报错，m-team页面报错“請求過於頻繁”。
请问有能修改执行频率的参数吗？比如半小时或者一小时运行一次。我查看运行日志，猜测执行的频率是5分钟一次。这样对站点的访问压力也较大。

运行环境：
Linux nas 6.1.0-20-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11) x86_64 GNU/Linux

报错日志：
2024-06-24 17:32:06,360 - 140037737060160 - INFO - search adult success.
2024-06-24 17:32:06,360 - 140037737060160 - ERROR - Search error:<bound method ClientResponse.text of <ClientResponse(https://kp.m-team.cc/api/torrent/search) [200 None]>
<CIMultiDictProxy('Date': 'Mon, 24 Jun 2024 09:32:06 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains; preload', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '898bb56aef7a7c73-LAX', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400')>
>
2024-06-24 17:32:06,377 - 140037737060160 - INFO - search music success.
2024-06-24 17:32:06,377 - 140037737060160 - ERROR - Search error:<bound method ClientResponse.text of <ClientResponse(https://kp.m-team.cc/api/torrent/search) [200 None]>
<CIMultiDictProxy('Date': 'Mon, 24 Jun 2024 09:32:06 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains; preload', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '898bb56aff587c67-LAX', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400')>
>
2024-06-24 17:32:06,380 - 140037737060160 - ERROR - Exception on /rss [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apps/app.py", line 26, in get_mteam_acrive_top_rss
    rss_str = m_team.generate_rss(param)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apps/mteam/m_team.py", line 217, in generate_rss
    data = self.get_active_top(param)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apps/mteam/m_team.py", line 61, in get_active_top
    search_result.extend(results_queue.get_nowait()["data"])
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by xiaohaiGreen** [comment]
什么时候执行是由调用方触发的，比方说你用的是qbittorrent，就有qbittorrent触发，需要在qbittorrent上面调整调用频率，如设置-> rss-> rss阅读器->rss订阅源更新频率调大。这个服务本身是被动的，并不会主动触发mteam的接口。

**Comment by Walleloveeve** [comment]
收到，我这边修改qb的rss更新频率，尝试调低后再看看是否有报错。
